- ffmap/web/api.py
Here you can see it in action: https://monitoring.freifunk-franken.de/api/nodelist
It's used to generate the Freifunk community files and also for the Freifunk map.
> Added nodelist API endpoint.

- ffmap/web/static/js/map.js
mehrere tilelayer zur Auswahl fuer die Karte.
Note: Ich habe mir nicht den kompletten Webstack aufgesetzt um es zu testen, es ist daher nicht ausgeschlossen dass irgendwo ein Fipptehler im Sinne fehlendes Komma oder Strichpunkt drin ist.
Known problems: der ausgewaehlte Kartenlayer ist nicht in die URL codiert.
> mehrere tilelayer zur Auswahl

- ffmap/web/templates/router.html
Netmon Sync Button auf Route Seite entfernt
> Netmon Sync Button entfernt

- ffmap/db/hoods.py
> Added hood Adelsdorf.

- ffmap/web/filters.py
See https://mantis.freifunk-franken.de/view.php?id=42 for more information.
The patch is already live.
> Removed padding for link local addresses

- ffmap/routertools.py
Signed-off-by: Adrian Schmutzler <freifunk@adrianschmutzler.de>
> Show WAN uplink based on nodewatcher xml entry and include L2TP for older firmware

- ffmap/db/hoods.py
Re-positioned Hood Adelsdorf
Re-positioned Hood Forchheim
Add Hood ErlangenWest
> Projekt Hoodteilung extremo #1

- ffmap/db/hoods.py
> Projekt Hoodteilung extremo #2

- ffmap/db/hoods.py
Add Hood Bayreuth
HoodID 21 is reserved for Lauf, it is created in the next steps
>  Projekt Hoodteilung extremo #3

- ffmap/db/hoods.py
Re-positioned Hood Markredwitz
Re-positioned Hood Hof
Add Hood Fichtelberg
Add Hood Rehau
> Projekt Hoodteilung extremo #4

- ffmap/db/hoods.py
Add Hood Ebern
HoodID 25 is reserved for Coburg, it is created in the next steps
> Projekt Hoodteilung extremo #5

- ffmap/db/hoods.py
Add Hood Arnstein
Re-positioned Hood Aschaffenburg
> Projekt Hoodteilung extremo #6

- ffmap/db/hoods.py
> Projekt Hoodteilung extremo #7

- ffmap/db/hoods.py
> Projekt Hoodteilung extremo #8

- ffmap/db/hoods.py
> Projekt Hoodteilung extremo #9

- ffmap/web/api.py
Hier ist ein Block mit Leerzeichen, während der Rest mit Tabs eingerückt ist. Hat mich einiges an Zeit gekostet, bis mir das beim Debuggen von zusammenkopiertem Code aufgefallen ist ... ;-)
> Harmonize tab style in api.py

- ffmap/web/api.py
Syntax: /api/wifianal/&lt;hood&gt;
This returns raw text.
> Add WifiAnalyzer alias file output

- ffmap/web/api.py
I would like this API script as I have a self-made C# administration program for my routers based on the monitoring.
At the moment, I'm parsing the routers overview html page which is not very nice or efficient...
This would make it much easier (and include the mac addresses)
> Add API script to output JSON list of routers with MAC address

- ffmap/web/static/js/graph.js
- ffmap/web/templates/router.html
Fixes #55
Signed-off-by: Adrian Schmutzler <freifunk@adrianschmutzler.de>
> Add loadavg graph for routers

- ffmap/web/templates/index.html
Signed-off-by: Adrian Schmutzler <freifunk@adrianschmutzler.de>
> No legacy anymore: Fix missing firmware

- ffmap/mapnik/hoodsv2.xml
- ffmap/mapnik/mkcsv.py
- ffmap/mapnik/run.sh
- ffmap/mapnik/tilestache.cfg
- ffmap/maptools.py
- ffmap/web/application.py
- ffmap/web/static/js/map.js
- install.sh
Draft version. On my local setup, I had to create CSVs manually
with mkcsv.py and copy them to /var/...
Hier bräuchte ich noch ein bisschen Unterstützung!
Signed-off-by: Adrian Schmutzler <freifunk@adrianschmutzler.de>
> fff-map: Add layer for KeyExchange v2
